language: python

sudo: true

env:
    global:
        - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/tests:$TRAVIS_BUILD_DIR/matchzoo

matrix:
    include:
        - os: linux
          dist: trusty
          python: 3.6
        - os: osx
          osx_image: xcode7.2
          language: generic
          env: PYTHON_VERSION=3.6

install:
  - "pip install -r requirements.txt"
  - "python -m nltk.downloader punkt"
  - "python -m nltk.downloader wordnet"
  - "python -m nltk.downloader stopwords"

script: make test

after_success:
      - codecov